In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [4]:
b = np.array([[9, 0, 8, 0, 7, 0], [6, 0, 5, 0, 4, 0]])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [6]:
# Get Dimension
a.ndim

1

In [7]:
# Get shape
a.shape

(3,)

In [8]:
# Get Type
a.dtype

dtype('int64')

In [10]:
c = np.array([1, 2, 3], dtype='int16')
d = np.array([1, 2, 3], dtype='int32')
e = np.array([1, 2, 3], dtype='int64')
f = np.array([1, 2, 3], dtype='int8')


In [11]:
# Get type
print(f' c type: {c.dtype} \n d type: {d.dtype} \n e type: {e.dtype} \n f type: {f.dtype}')

 c type: int16 
 d type: int32 
 e type: int64 
 f type: int8


In [12]:
# Get size
print(f' c size: {c.itemsize} \n d size: {d.itemsize} \n e size: {e.itemsize} \n f size: {f.itemsize}')

 c size: 2 
 d size: 4 
 e size: 8 
 f size: 1


In [13]:
# Get total size
print(f' c size: {c.nbytes} \n d size: {d.nbytes} \n e size: {e.nbytes} \n f size: {f.nbytes}')

 c size: 6 
 d size: 12 
 e size: 24 
 f size: 3


In [15]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Get specific  element [r, c]
a[1, -2]

13

In [18]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
# Get specific column
a[:, 2]

array([ 3, 10])

In [21]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [22]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [24]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [26]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

In [27]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [30]:
# Any other number like 99
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [31]:
# Any other number(full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
# Random decimal numbers between 0 and 1
np.random.rand(4, 2, 3)

array([[0.03356956, 0.78098777],
       [0.40524891, 0.74323597],
       [0.1550907 , 0.4999768 ],
       [0.62864285, 0.51661486]])

In [34]:
np.random.random_sample(a.shape)

array([[0.38726656, 0.26207946, 0.33377016, 0.57599169, 0.39423031,
        0.07223441, 0.43650906],
       [0.98452695, 0.25160435, 0.45387586, 0.4219668 , 0.95808021,
        0.2621346 , 0.04757797]])

In [36]:
# Random Integer values
np.random.randint(-10, 7, size=(3, 3))

array([[-4,  3,  4],
       [ 3, -3, -2],
       [-1, -3, -4]])

In [37]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [40]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [41]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [44]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [46]:
b[0] = 100

In [47]:
print(b)
print(a)

[100   2   3]
[100   2   3]


In [48]:
a = np.array([1, 2, 3])
b = a.copy()
b

array([1, 2, 3])

### Mathematics

In [49]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [50]:
a + 2

array([3, 4, 5, 6])

In [52]:
a - 2

array([-1,  0,  1,  2])

In [53]:
a * 2

array([2, 4, 6, 8])

In [54]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [55]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [56]:
a ** 2

array([ 1,  4,  9, 16])

In [57]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [58]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [59]:
# Take the tan
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

##### Linear Algebra

In [61]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
b = np.full((3, 2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [64]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [66]:
# Find determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [68]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.min(stats)

1

In [70]:
np.max(stats)

6

In [71]:
np.min(stats, axis=1)

array([1, 4])

In [72]:
np.min(stats, axis=0)

array([1, 2, 3])

In [73]:
np.sum(stats)

21

#### Reorganizing array

In [74]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [76]:
print(before.shape)

(2, 4)


In [78]:
after = before.reshape((8, 1))
print(after)
before.reshape((2, 2, 2))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [80]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
np.vstack([v1, v1, v1, v1, v2, v2, v2, v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h1, h1, h])